runtime: python
env: flex
entrypoint: gunicorn -t 0 -b :$PORT main:server

runtime_config:
    python_version: 3.7

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cpu_utilization:
    target_utilization: 0.8

resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 20